apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::900880114779:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-Qa9WwIyAljKC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::900880114779:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-30T11:44:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1372"
  uid: 730f5e93-92db-425c-9bd0-cca17bd564d4
